/*
 * generated by Xtext 2.10.0
 */
package at.jku.weiner.mttf.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MttfUiModule extends AbstractMttfUiModule {
}
