/*
 * generated by Xtext 2.10.0
 */
package at.jku.weiner.mttf


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MttfStandaloneSetup extends MttfStandaloneSetupGenerated {

	def static void doSetup() {
		// new org.eclipse.emf.mwe.utils.StandaloneSetup().setPlatformUri("../");
		new MttfStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
