/*
 * generated by Xtext 2.10.0
 */
package at.jku.weiner.mttf.tests

import at.jku.weiner.mttf.mttf.TestSuite
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import at.jku.weiner.mttf.validation.MttfValidator
import at.jku.weiner.mttf.mttf.MttfPackage
import at.jku.weiner.mttf.utils.EclipseUtilities

@RunWith(XtextRunner)
@InjectWith(MttfInjectorProvider)
class MttfParsingTest{

	@Inject
	ParseHelper<TestSuite> parseHelper
	@Inject 
	ValidationTestHelper validationHelper

	@Test 
	def void testSimpleTestSuite() {
		System.out.println("testSimpleTestSuite-begin");
		val result = parseHelper.parse('''
			test-suite
				source-metamodel="platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Class.xmi"
				target-metamodel="platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Relational.xmi"
				transformation="platform:/plugin/at.jku.weiner.mttf.tests/transformations/Class2Relational.atl"
		''')
		Assert.assertNotNull(result)
		validationHelper.assertNoErrors(result)
		Assert.assertNull(result.name)
		val sut = result.sut
		Assert.assertNotNull(sut)
		val sourceMM = sut.sourceMetaModel
		Assert.assertNotNull(sourceMM)
		Assert.assertEquals("platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Class.xmi", sourceMM.uri);
		val targetMM = sut.targetMetaModel
		Assert.assertNotNull(targetMM)
		Assert.assertEquals("platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Relational.xmi", targetMM.uri);
		val trafo = sut.transformationUnderTest
		Assert.assertNotNull(trafo)
		Assert.assertEquals("platform:/plugin/at.jku.weiner.mttf.tests/transformations/Class2Relational.atl", trafo.uri);
		Assert.assertNotNull(result.testCases)
		Assert.assertTrue(result.testCases.isEmpty())
		System.out.println("testSimpleTestSuite-end");
	}
	
	@Test
	def void testSimpleTestSuiteWithName() {
		val result = parseHelper.parse('''
			test-suite name=Class2Relational_TestSuite
				source-metamodel="platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Class.xmi"
				target-metamodel="platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Relational.xmi"
				transformation="platform:/plugin/at.jku.weiner.mttf.tests/transformations/Class2Relational.atl"
		''')
		Assert.assertNotNull(result)
		validationHelper.assertNoErrors(result)
		Assert.assertEquals("Class2Relational_TestSuite", result.name)
	}
	
	@Test
	def void testSimpleTestSuiteWithCopyingPluginToResource() {
		//copy files
		val src = "platform:/plugin/at.jku.weiner.mttf.tests";
		val dst = "platform:/resource/my-test";
		val project = EclipseUtilities.copyProject(src, dst, true);
		Assert.assertNotNull(project);
		Assert.assertTrue(project.exists());
		// ...
		val result = parseHelper.parse('''
			test-suite name=Class2Relational_TestSuite
				source-metamodel="platform:/resource/my-test/metamodels/Class.xmi"
				target-metamodel="platform:/resource/my-test/metamodels/Relational.xmi"
				transformation="platform:/resource/my-test/transformations/Class2Relational.atl"
		''')
		Assert.assertNotNull(result)
		validationHelper.assertNoErrors(result)
	}
	
	@Test
	def void testSimpleTestSuiteWithEmptySourceMM() {
		val result = parseHelper.parse('''
			test-suite name=Class2Relational_TestSuite
				source-metamodel=""
				target-metamodel="platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Relational.xmi"
				transformation="platform:/plugin/at.jku.weiner.mttf.tests/transformations/Class2Relational.atl"
		''')
		Assert.assertNotNull(result)
		validationHelper.assertError(result, MttfPackage::eINSTANCE.sourceMetaModel, 
			MttfValidator.SOURCE_MM_IS_EMPTY, MttfValidator.MSG_SOURCE_MM_IS_EMTPY
		);
	}
	
	@Test
	def void testSimpleTestSuiteWithEmptyTargetMM() {
		val result = parseHelper.parse('''
			test-suite name=Class2Relational_TestSuite
				source-metamodel="platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Class.xmi"
				target-metamodel=""
				transformation="platform:/plugin/at.jku.weiner.mttf.tests/transformations/Class2Relational.atl"
		''')
		Assert.assertNotNull(result)
		validationHelper.assertError(result, MttfPackage::eINSTANCE.targetMetaModel, 
			MttfValidator.TARGET_MM_IS_EMPTY, MttfValidator.MSG_TARGET_MM_IS_EMTPY
		);
	}
	
	@Test
	def void testSimpleTestSuiteWithEmptyTrafo() {
		val result = parseHelper.parse('''
			test-suite name=Class2Relational_TestSuite
				source-metamodel="platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Class.xmi"
				target-metamodel="platform:/plugin/at.jku.weiner.mttf.tests/metamodels/Relational.xmi"
				transformation=""
		''')
		Assert.assertNotNull(result)
		validationHelper.assertError(result, MttfPackage::eINSTANCE.transformationUnderTest, 
			MttfValidator.TRAFO_IS_EMPTY, MttfValidator.MSG_TRAFO_IS_EMTPY
		);
	}

}
